### PR TITLE
fix: add requests as a dependency

### LINKED ISSUE #268: requests is missing as dependency
`requests` is used directly by several modules in this project, see https://github.com/googleapis/python-storage/search?l=Python&q=requests yet it's not listed in `setup.py` in `install_requires`.

(note that this won't be an issue for most people because `requests` is pulled in as a dependency by one of the dependencies that are currently listed).

### PR DESCRIPTION
**Pull request by HemangChothani**
Fixes #268

### CODE REVIEW

**Review by andrewsg — APPROVED** [review]
Thank you for taking the time to submit this.

**Comment by andrewsg** [comment]
Build error looks unrelated at first glance, but we need to investigate before merging

**Comment by HemangChothani** [comment]
System test issue will be fixed by PR https://github.com/googleapis/python-storage/pull/273

**Comment by plamut** [comment]
Restricting the PubSub version to `<2.0.0` indeed helped, system tests now pass again.

**Pull request merged**
