### PR TITLE
Fix typo in docs: paramters -> parameters

### PR DESCRIPTION
**Pull request by vegarsti**
Just a docs update, so no body here.

### CODE REVIEW

**Comment by vegarsti** [comment]
@googlebot I signed it!

**Comment by vegarsti** [comment]
Shall I merge it? If so, how can I make the checks pass? Or will you take care of that?

**Comment by frankyn** [comment]
I need to rerun tests (kicked off) and I've enabled merge on green once everything is passing.

**Comment by vegarsti** [comment]
🙏

**Pull request merged**
