### PR TITLE
refactor: move methods to client class

### LINKED ISSUE #38: Proposal: move API-methods to client
The Cloud Storage Python client was one of the first google-cloud-python clients, intended to be more reliable and more Pythonic than the google-api-client that it replaced. It is also a 100% hand-written client. Because it predates the auto-generated google-cloud-python clients, the Cloud Storage Python client has inconsistencies with other google-cloud-python clients.

This design proposal is to bring the Cloud Storage client further into alignment with other google-cloud-python clients and make the eventual inclusion of an auto-generated gRPC transport layer less disruptive to users of the Cloud Storage client.

**Design document:**

https://docs.google.com/document/d/1A4FIxThZK_enK7OV9ChY54IPrlpbdHwuhvVEu6iTHxM/edit?usp=sharing

Please share your feedback on the specifics of this as comments in the [design document](https://docs.google.com/document/d/1A4FIxThZK_enK7OV9ChY54IPrlpbdHwuhvVEu6iTHxM/edit?usp=sharing).

CC @crwilcox @frankyn @lbristol88 

**Update**: according to [comment](https://github.com/googleapis/google-cloud-python/pull/8604#pullrequestreview-313722140), we need to update samples for moved methods before deprecating the old ones.

### PR DESCRIPTION
**Pull request by HemangChothani**
Fixes #38

### CODE REVIEW

**Review by andrewsg — APPROVED** [review]
LGTM

**Comment by andrewsg** [comment]
@tswast In the bug you said, "we need to update samples for moved methods before deprecating the old ones." Is this change okay as-is, or do we need to make this change without the deprecation warning first, then update samples, then add the deprecation warning?

**Comment by tswast** [comment]
If it helps you find the samples that need to be updated, I'm okay merging this PR first. It's just a bad look if we have samples on cloud.google.com that show deprecation warnings.

**Comment by andrewsg** [comment]
I agree. But we can't update the sample without pushing part of this change, so @HemangChothani Let's omit the deprecation warning for now and open an issue to update the samples, then add the deprecation warning in that order.

**Comment by HemangChothani** [comment]
@andrewsg Opend an issue https://github.com/GoogleCloudPlatform/python-docs-samples/issues/5031 to update the samples.

**Comment by HemangChothani** [comment]
@andrewsg  I have opend an issue to update sample  https://github.com/GoogleCloudPlatform/python-docs-samples/issues/5031 in python-docs-sample repo , but i didn't find any sample needs to update, should i open issue in `python-storage` repo to update snippets and system-tests for `list_blobs` and `download_to_file` methods

**Comment by frankyn** [comment]
@andrewsg and @HemangChothani, I replied to the issue. We are only missing updates for  download_to_filename.

**Comment by HemangChothani** [comment]
@frankyn we have moved ` download_to_file` into the client class, ` download_to_filename` is still in the blob class so i think there is no need to update any sample.

 ` blob.download_to_filename`  is calling `blob.download_to_file` method which is deprecated now, so  i will update soon and direct call the method `client.download_to_file` method.

Also update the method call from `bucket.list_blobs` to `client.list_blobs`.

**Comment by frankyn** [comment]
Why was only download_to_file updated but not download_to_filename?

**Comment by HemangChothani** [comment]
Document mentioned in issue https://github.com/googleapis/python-storage/issues/38, found `download_to_file` and `list_blobs` methods need to move implementation from blob class to client class and deprecate older one.

**Pull request merged**
